name: hrana
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.0
  protobuf: ^3.1.0
  sqlite3: ^2.4.4
  stream_channel: ^2.1.2
  web_socket_channel: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
